runtime: php82

env_variables:
  APP_KEY: ${APP_KEY}
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://api.yourdomain.com"
  
  DB_CONNECTION: "mysql"
  DB_HOST: "/cloudsql/YOUR_PROJECT_ID:YOUR_REGION:YOUR_INSTANCE"
  DB_PORT: "3306"
  DB_DATABASE: "miftah_sso"
  DB_USERNAME: "miftah_user"
  DB_PASSWORD: ${DB_PASSWORD}
  
  REDIS_HOST: "10.0.0.1"
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  REDIS_PORT: "6379"
  
  SESSION_DRIVER: "redis"
  CACHE_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
  
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  
  SANCTUM_STATEFUL_DOMAINS: "yourdomain.com"
  SESSION_DOMAIN: ".yourdomain.com"

handlers:
  - url: /robots.txt
    static_files: public/robots.txt
    upload: public/robots.txt

  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico

  - url: /.*
    script: auto

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

entrypoint: serve public/index.php

beta_settings:
  cloud_sql_instances: "YOUR_PROJECT_ID:YOUR_REGION:YOUR_INSTANCE"